name: TactileModel
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.12.14=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.11=py39hf88036b_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - importlib-metadata=8.5.0=pyha770c72_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.12.0=pyh41d4057_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - keyboard==0.13.5
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libedit=3.1.20191231=he28a2e2_2
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - liblzma=5.6.3=hb9d3cd8_1
  - libnsl=2.0.1=hd590300_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.47.2=hee588c1_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=he02047a_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.4.0=hb9d3cd8_0
  - packaging=24.2=pyhd8ed1ab_2
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=24.3.1=pyh8b19718_2
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prompt-toolkit=3.0.48=pyha770c72_1
  - prompt_toolkit=3.0.48=hd8ed1ab_1
  - psutil=6.1.0=py39h8cd3c5a_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.18.0=pyhd8ed1ab_1
  - python=3.9.21=h9c0c6dc_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.9=5_cp39
  - pyzmq=26.2.0=py39h4e4fb57_3
  - readline=8.2=h8228510_1
  - setuptools=75.6.0=pyhff2d567_1
  - six=1.17.0=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.2=py39h8cd3c5a_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - pip:
    - absl-py==2.1.0
    - addict==2.4.0
    - ale-py==0.10.1
    - alembic==1.14.0
    - attrs==24.3.0
    - blinker==1.9.0
    - box2d-py==2.3.5
    - certifi==2024.12.14
    - cffi==1.17.1
    - charset-normalizer==3.4.1
    - chex==0.1.88
    - click==8.1.8
    - cloudpickle==3.1.0
    - cmake==3.25.0
    - colorama==0.4.6
    - colorlog==6.9.0
    - configargparse==1.7
    - contourpy==1.3.0
    - cycler==0.12.1
    - cython==0.29.37
    - dash==2.18.2
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - dill==0.3.9
    - etils==1.5.2
    - evdev==1.7.1
    - farama-notifications==0.0.4
    - fasteners==0.19
    - fastjsonschema==2.21.1
    - filelock==3.13.1
    - flask==3.0.3
    - flax==0.8.5
    - fonttools==4.55.3
    - freetype-py==2.5.1
    - fsspec==2024.2.0
    - glfw==2.8.0
    - greenlet==3.1.1
    - grpcio==1.68.1
    - gymnasium==1.0.0
    - h5py==3.12.1
    - humanize==4.11.0
    - idna==3.10
    - imageio==2.36.1
    - imageio-ffmpeg==0.5.1
    - importlib-resources==6.4.5
    - ipywidgets==8.1.5
    - itsdangerous==2.2.0
    - jax==0.4.30
    - jaxlib==0.4.30
    - jinja2==3.1.3
    - joblib==1.4.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - jupyterlab-widgets==3.0.13
    - kiwisolver==1.4.7
    - lazy-loader==0.4
    - lightgbm==4.5.0
    - lit==15.0.7
    - mako==1.3.8
    - markdown==3.7
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.9.4
    - mdurl==0.1.2
    - mesh-to-sdf==0.0.15
    - ml-dtypes==0.5.0
    - moviepy==2.1.1
    - mpmath==1.3.0
    - msgpack==1.1.0
    - mujoco==3.2.6
    - mujoco-py==2.1.2.14
    - nbformat==5.10.4
    - networkx==3.2.1
    - numpy==1.26.3
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cuda-cupti-cu11==11.8.87
    - nvidia-cuda-nvrtc-cu11==11.8.89
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cudnn-cu11==8.7.0.84
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.3.0.86
    - nvidia-cusolver-cu11==11.4.1.48
    - nvidia-cusparse-cu11==11.7.5.86
    - nvidia-nccl-cu11==2.20.5
    - nvidia-nvtx-cu11==11.8.86
    - open3d==0.18.0
    - opencv-python==4.10.0.84
    - opensimplex==0.4.5.1
    - opt-einsum==3.4.0
    - optax==0.2.4
    - optuna==4.1.0
    - optuna-integration==4.1.0
    - orbax-checkpoint==0.6.4
    - pandas==2.2.3
    - pettingzoo==1.24.3
    - pillow==10.2.0
    - plotly==5.24.1
    - plyfile==1.1
    - proglog==0.1.10
    - protobuf==5.29.2
    - pybullet==3.2.6
    - pycparser==2.22
    - pygame==2.6.1
    - pyglet==2.0.20
    - pynput==1.7.7
    - pyopengl==3.1.7
    - pyopengl-accelerate==3.1.7
    - pyparsing==3.2.0
    - pyquaternion==0.9.9
    - pyrealsense2==2.56.5.9235
    - pyrender==0.1.45
    - python-dotenv==1.0.1
    - python-xlib==0.33
    - pytz==2024.2
    - pywavefront==1.3.3
    - pyyaml==6.0.2
    - referencing==0.35.1
    - requests==2.32.3
    - retrying==1.3.4
    - rich==13.9.4
    - rpds-py==0.22.3
    - scikit-image==0.24.0
    - scikit-learn==1.6.0
    - scipy==1.13.1
    - sqlalchemy==2.0.36
    - stable-baselines3==2.4.0
    - swig==4.3.0
    - sympy==1.13.1
    - tabulate==0.9.0
    - tactile-gym==0.0.1
    - taichi==1.7.2
    - tenacity==9.0.0
    - tensorboard==2.18.0
    - tensorboard-data-server==0.7.2
    - tensorstore==0.1.69
    - threadpoolctl==3.5.0
    - tifffile==2024.8.30
    - toolz==1.0.0
    - torch==2.0.0+cu118
    - torchaudio==2.0.1+cu118
    - torchvision==0.15.1+cu118
    - tqdm==4.67.1
    - trimesh==4.5.3
    - triton==2.0.0
    - typing-extensions==4.9.0
    - tzdata==2024.2
    - urllib3==2.3.0
    - werkzeug==3.0.6
    - widgetsnbextension==4.0.13
    - xxhash==3.5.0
prefix: /home/yxw/anaconda3/envs/robcare1
